services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: 594538768076.dkr.ecr.us-east-1.amazonaws.com/hord-cms-ec2:web
    expose:
      - 8000
    volumes:
      - static-data:/vol/web
      - media_volume:/home/app/web/mediafiles
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 443:443
      - 80:8000
    volumes:
      - static-data:/vol/static
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  acme-companion:
    env_file:
      - ./.env.prod.proxy-companion
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx

volumes:
  postgres-data:
  static-data:
  media_volume:
  certs:
  html:
  vhost:
  acme:
