services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: 594538768076.dkr.ecr.us-east-1.amazonaws.com/hord-cms-ec2:web-1
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env.staging
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    image: 594538768076.dkr.ecr.us-east-1.amazonaws.com/hord-cms-ec2:nginx-proxy-1
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
