# Generated by Django 3.2.23 on 2024-01-15 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='product',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.quantitativeunit'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default='', verbose_name='expiration date'),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='person',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.quantitativeunit'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='person',
        ),
        migrations.AddField(
            model_name='recipe',
            name='person',
            field=models.ManyToManyField(blank=True, default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
