# Generated by Django 3.2.23 on 2024-01-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20240115_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
