# Generated by Django 4.2.3 on 2026-07-12 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_alter_inventoryitem_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='person',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
