# Generated by Django 3.2.23 on 2024-01-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
