# Generated by Django 4.2.3 on 2024-06-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
