---
name: Build
on: [pull_request_target]

env:
  DOCKER_NAMESPACE: "jami"
  IMAGE_NAME: "hord"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
